# Generated by Django 5.1.7 on 2025-06-30 14:50

import Product_app.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('OEM_no', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('urgency', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea')], max_length=10)),
                ('packing_type', models.CharField(blank=True, choices=[('BOX', 'Box'), ('TUBE', 'Tube')], max_length=10, null=True)),
                ('marking_instructions', models.TextField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=Product_app.models.upload_product_image)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
